### ISSUE TITLE
Module not found: Can't resolve 'styled-jsx/style'

### ISSUE THREAD

**Issue by jbrozena22** [beizhedenglong/react-multi-crops#1]
Thanks for making this, very cool. Quick question though. When I add it to my react project i'm getting this error:

./~/react-multi-crops/lib/components/Icons.js
Module not found: Can't resolve 'styled-jsx/style'

I see styled-jsx is a dev dependency in package.json but not in production, could that be the issue?

**Comment by jbrozena22** [comment]
I noticed the source committed here doesn't have the issue. Maybe you just need to upload the latest to NPM?

**Comment by beizhedenglong** [comment]
@jbrozena22 fixed this issue in  version 0.0.8
