### ISSUE TITLE
Render cropped image

### ISSUE THREAD

**Issue by dturakhia** [beizhedenglong/react-multi-crops#4]
Thanks for this really cool tool. I was wondering if there was a way to display the selected cropped image?

**Comment by beizhedenglong** [comment]
@dturakhia This library is  used to  save coordinates。You can crop the background image by using `canvas `，like this [example](https://stackoverflow.com/questions/26015497/how-to-resize-then-crop-an-image-with-canvas)。Or send coordinates to server，then send cropped images back to client。

**Comment by dturakhia** [comment]
@beizhedenglong thanks, I'll try it in the way you mentioned
