### ISSUE TITLE
Can drag and resize crop box out of the image

### ISSUE THREAD

**Issue by gaurav10069** [beizhedenglong/react-multi-crops#5]
Hi, we can drag or resize cropbox out of the image

**Comment by beizhedenglong** [comment]
Hi, this was designed on purpose. if want to constrain rectangles inside the image boundary. you can validate the changing rectangle inside `onChange`, like this:

```js
changeCoordinate = (coordinate, index, coordinates) => {
    // if width greater than 100px, we just ignore it
    if (coordinate.width > 100) {
      return
    }
    this.setState({
      coordinates,
    })
  }

```
maybe I will add some props to make this easy when I have time

**Comment by gaurav10069** [comment]
Hi , thanks for your response. I am able to do that now this way:

 changeCoordinate = (coordinate, index, coordinates) => {
    let img_height = document.getElementById('crop_div').clientHeight
    if (coordinate.width+coordinate.x > 1000 || coordinate.x <=0) {
        return
      } 
    if (coordinate.height+coordinate.y > img_height || coordinate.y <=0) {
        return
      } 
    this.setState({
      coordinates,
    })
  }
