### ISSUE TITLE
Add props for prevent overlap of cropArea - Feature Requests

### ISSUE THREAD

**Issue by CriptoCosmo** [beizhedenglong/react-multi-crops#6]
I ask for a property that prevents overlapping areas as follows
```jsx
<MultiCrops
    src={img}
    width={1000}
    coordinates={this.state.coordinates}
    onChange={this.changeCoordinate}
    onDelete={this.deleteCoordinate}
    //PROPS
    permitAreaOverlap={false} //default true
/>
```

**Comment by beizhedenglong** [comment]
@CriptoCosmo hi, you can check whether to include current coordinate in `onChange` handler.

I will add more controllable features when I have time.

**Comment by CriptoCosmo** [comment]
Hi @beizhedenglong, i have create the functionality and open a pull request, follow is the demo 

![screencast-localhost-3000-2019 05 23-11-40-24](https://user-images.githubusercontent.com/17647067/58245185-85619300-7d54-11e9-9b51-0ce4c351e090.gif)

bye @CriptoCosmo  ;)

**Comment by beizhedenglong** [comment]
These rectangles still overlap when resizing or drawing

**Comment by CriptoCosmo** [comment]
fixed and open pull request

**Comment by beizhedenglong** [comment]
@CriptoCosmo Hi, you can implement similar functionality in `onChange` handler like this:
```js
changeCoordinate = (coordinate, index, coordinates = []) => {
    const left = ({ x }) => x
    const right = ({ x, width }) => x + width
    const top = ({ y }) => y
    const bottom = ({ y, height }) => y + height
    const isOverlap = (rectA, rectB) => !(
      (left(rectA) > right(rectB)) ||
      (right(rectA) < left(rectB)) ||
      (bottom(rectA) < top(rectB)) ||
      (top(rectA) > bottom(rectB))
    )
    const someOverlap = coordinates.some((rectB, i) =>
      (i !== index) && isOverlap(coordinate, rectB))
    if (!someOverlap) {
      this.setState({
        coordinates,
      })
    }
  }

```

The current API and implementation of this package were not carefully designed. I will refactor the code base in the next several weeks and make it easier to use.
