### ISSUE TITLE
Restriction to parent

### ISSUE THREAD

**Issue by CriptoCosmo** [beizhedenglong/react-multi-crops#8]
Hi @beizhedenglong 

when you try to drag the crop area outside of the parent container (same size defined from props 'width' and 'height') it dont stop.
I have see your code and i see that you use interactjs and i have found a possible solution in his documentation,
``` javascript
interact('.draggable')
  .draggable({
    // enable inertial throwing
    inertia: true,
    // keep the element within the area of it's parent
    modifiers: [
      interact.modifiers.restrict({
        restriction: "parent",
        endOnly: true,
        elementRect: { top: 0, left: 0, bottom: 1, right: 1 }
      }),
    ]
)
```
let me know

**Comment by beizhedenglong** [comment]
see this issue https://github.com/beizhedenglong/react-multi-crops/issues/5

**Comment by CriptoCosmo** [comment]
thanks
